version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vergen
    versions:
    - 4.0.1
    - 4.1.0
    - 4.2.0
    - 5.0.0
  - dependency-name: env_logger
    versions:
    - 0.8.2
  - dependency-name: crossbeam-channel
    versions:
    - 0.5.0
